In [1]:
#Import Libraries
import numpy as np

In [2]:
def micro_f1_score(y_true, y_pred):
    """Function ot calculate micro average F1 score in a multi class setting"""

    #number of classes
    actual_labels = np.unique(y_true)
    
    #confusion matrix initialized to zeros
    confusion_matrix = np.zeros((len(actual_labels), len(actual_labels)))
    
    #update confusion matrix according to y_true and y_pred
    for i in zip(y_pred, y_true):
        confusion_matrix[(i)] += 1

    #calculate True Positives, False Positives and False Negatives for each class
    tps = confusion_matrix.diagonal()
    fns = confusion_matrix.sum(axis=0)-tps
    fps = confusion_matrix.sum(axis=1)-tps
    
    #Calculate Precision and Recall across all classes
    precision = tps.sum()/(tps.sum()+fps.sum())
    recall = tps.sum()/(tps.sum()+fns.sum())
    
    #Calculate F1 score
    micro_avg_f1 = 2*precision*recall/(precision+recall)
    
    return confusion_matrix, micro_avg_f1

In [6]:
y_true = np.array([0,0,0,0,0,1,1,1,1,1,2,2,2,2,2,3,3,3,3,3])
y_pred = np.array([1,2,0,0,3,1,3,2,1,1,3,2,2,1,0,3,0,0,1,1])

cm,f1 = micro_f1_score(y_true,y_pred)

print("Confusion Matrix\n\n",cm)
print("\n\nMicro Average F1 Score: ",f1)

Confusion Matrix

 [[2. 0. 1. 2.]
 [1. 3. 1. 2.]
 [1. 1. 2. 0.]
 [1. 1. 1. 1.]]


Micro Average F1 Score:  0.4000000000000001
